import { CheckCircle2, Database, ImageIcon, Layers3, Palette, Route, ShieldCheck } from "lucide-react";
import { Card } from "@/components/ui/card";
import { designRecipes, sectionVariants, serviceCategories, stylePresets } from "@/lib/design-system/catalog";
import { previewAssetManifest } from "@/lib/design-system/preview-manifest";

export default function DesignStudioPage() {
  const groups = Object.entries(Object.groupBy(sectionVariants, (variant) => variant.sectionType));
  const stats = [
    { label: "Section Variants", value: sectionVariants.length, icon: Layers3 },
    { label: "Style Presets", value: stylePresets.length, icon: Palette },
    { label: "Published Recipes", value: designRecipes.filter((item) => item.status === "published").length, icon: Route },
    { label: "Mapped Categories", value: serviceCategories.length, icon: Database }
  ];
  return <div className="space-y-7"><div><p className="text-sm font-bold uppercase tracking-widest text-brand-700">Internal tools</p><h1 className="mt-2 text-3xl font-bold text-ink">Design Studio</h1><p className="mt-2 max-w-3xl text-muted">Approved modular variants, presets, recipes, compatibility rules and preview readiness for the Service Business family.</p></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon }) => <Card key={label} className="p-5"><Icon className="text-brand-700" size={21} /><p className="mt-4 text-sm font-semibold text-muted">{label}</p><p className="mt-1 text-3xl font-bold text-ink">{value}</p></Card>)}</section>
    <section><h2 className="text-xl font-bold text-ink">Section Variants</h2><div className="mt-3 grid gap-4 lg:grid-cols-2">{groups.map(([type, variants]) => <Card key={type} className="p-5"><div className="flex items-center justify-between"><h3 className="font-bold capitalize text-ink">{type.replace("-", " ")}</h3><span className="rounded-full bg-canvas px-3 py-1 text-xs font-bold text-muted">{variants.length}</span></div><div className="mt-3 divide-y divide-line">{variants.map((variant) => <div key={variant.id} className="py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-ink">{variant.name}</p><p className="mt-1 text-xs text-muted">Fallback: {variant.fallbackVariant ?? "none"}</p></div><span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><ShieldCheck size={14} />QA ready</span></div></div>)}</div></Card>)}</div></section>
    <section><h2 className="text-xl font-bold text-ink">Style Presets</h2><div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{stylePresets.map((preset) => <Card key={preset.id} className="p-4"><div className="flex gap-1">{[preset.colors.primary, preset.colors.secondary, preset.colors.accent].map((color) => <span key={color} className="size-8 rounded-full border border-white" style={{ backgroundColor: color }} />)}</div><h3 className="mt-4 font-bold text-ink">{preset.name}</h3><p className="mt-1 text-xs leading-5 text-muted">{preset.description}</p></Card>)}</div></section>
    <section><h2 className="text-xl font-bold text-ink">Design Recipes</h2><div className="mt-3 grid gap-4 lg:grid-cols-3">{designRecipes.map((recipe) => <Card key={recipe.id} className="p-5"><div className="flex items-center justify-between"><h3 className="font-bold text-ink">{recipe.name}</h3><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold capitalize text-emerald-800">{recipe.status}</span></div><p className="mt-2 text-sm leading-6 text-muted">{recipe.description}</p><p className="mt-4 text-xs font-bold text-muted">{recipe.sections.length} approved sections</p></Card>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="flex items-center gap-2 font-bold text-ink"><ImageIcon size={19} />Preview Assets</h2><div className="mt-3 grid gap-2">{Object.entries(previewAssetManifest).map(([slug, assets]) => <div key={slug} className="flex items-center justify-between rounded-lg bg-canvas p-3 text-sm"><span className="font-semibold text-ink">{slug}</span><span className="inline-flex items-center gap-1 font-bold text-emerald-700"><CheckCircle2 size={15} />{Object.keys(assets).length} assets</span></div>)}</div></Card><Card className="p-5"><h2 className="font-bold text-ink">QA Status</h2><div className="mt-3 grid gap-2">{["Draft", "Internal Review", "Mobile QA", "Desktop QA", "Approved", "Published", "Archived"].map((status, index) => <div key={status} className="flex items-center gap-3 text-sm"><span className={`size-2.5 rounded-full ${index <= 5 ? "bg-emerald-500" : "bg-slate-300"}`} /><span className="text-ink">{status}</span></div>)}</div></Card></section>
  </div>;
}
